[package]
name = "default-boxed"
version = "0.1.2"
description = "Helper trait to help create large struct on heap directly"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
license = "MIT"

[badges]
azure-devops = { project = "upsuper/upsuper", pipeline = "default-boxed", build = "1" }

[workspace]

[dependencies]
default-boxed-derive = { version = "0.1.2", path = "default-boxed-derive" }
