[package]
name = "default-boxed"
version = "0.1.1"
description = "Helper trait to help create large struct on heap directly"
authors = ["Xidorn Quan <me@upsuper.org>"]
edition = "2018"
license = "MIT"

[workspace]

[dependencies]
default-boxed-derive = { version = "0.1.1", path = "default-boxed-derive" }
